### ISSUE TITLE
Is it possible to provide instructions to run the generated system on PC host using qemu ?

### ISSUE THREAD

**Issue by karim-manaouil** [tolstoyevsky/pieman#155]
I wanted to run the system in a emulated environment but i can't get the correct cpu model and machine type for `qemu-system-arm`. Is it possible to provide informations and instructions for such a purpose ? Thanks.

**Comment by eugulixes** [comment]
Hello Karim
Now it's possible to run Ubuntu Bionic (64bit) built by Pieman for Raspberry Pi 3. Have a look at the nearby project: https://github.com/tolstoyevsky/mmb/tree/master/qemu.

**Comment by karim-manaouil** [comment]
Great job. Thanks
