### ISSUE TITLE
Enabling Interfacing options like I2C, SSH, etc.,

### ISSUE THREAD

**Issue by Beebeejohn** [tolstoyevsky/pieman#282]
How to enable i2c, ssh,etc. while building raspberry pi os image using piemann.  Can any one tell me how to enable it

**Comment by Beebeejohn** [comment]
I2c enabling option is there is config.txt file but for ssh how to enable it

**Comment by eugulixes** [comment]
Install the ssh package. For example, `sudo env INCLUDES=ssh pieman.sh`

**Comment by Beebeejohn** [comment]
So if I installed  ssh as you mentioned above, will it automatically gets enabled after flashing the OS in raspberry pi

**Comment by eugulixes** [comment]
Yes, it will

**Comment by Beebeejohn** [comment]
Ya ok thank you
